start:
	@./scripts/bin.sh start
.PHONY: start

tests:
	@./scripts/bin.sh tests
.PHONY: tests

up:
	@./scripts/bin.sh up
.PHONY: up

down:
	@./scripts/bin.sh down
.PHONY: down

migrate:
	@./scripts/bin.sh migrate
.PHONY: migrate

preprocess:
	@./scripts/bin.sh preprocess
.PHONY: preprocess

generate:
	@./scripts/bin.sh generate
.PHONY: generate

help:
	@./scripts/bin.sh help
.PHONY: help
